### ISSUE TITLE
can't perform GLM

### ISSUE THREAD

**Issue by isglobal-brge** [isglobal-brge/ShinyDataSHIELD#17]
When performing a GLM try to give a message like

Check whether the variables are properly written and/or your dependent variable fits the output family

when a error appears rather than "can't peform GLM")

(or maybe keep can't perform GLM and add what I wrote)

THE SAME APPLIES FOR OTHER COMPUTATIONS ... Always try to help users .. if not, you will receive naïve questions, or even worse, people won't use the app

**Comment by ESCRI11** [comment]
The error messages the server gives are not really informative for GLM.

Example: output family is set as *gaussian* for a *bionomial* variable

`"Command 'glmDS1(GENDER ~ LAB_TSC, \"gaussian\", NULL, NULL, \"tables_sm\")' failed on 'c2': Error while evaluating 'dsBase::glmDS1(GENDER~LAB_TSC, \"gaussian\", NULL, NULL, \"tables_sm\")' -> Error in glm.fit(x = structure(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  : \n  NA/NaN/Inf in 'y'\n"`

It is useful for miss-spelled variables:

`"Command 'glmDS1(GENDER ~ LAB_TSCSSAs, \"gaussian\", NULL, NULL, \"tables_sm\")' failed on 'c2': Error while evaluating 'dsBase::glmDS1(GENDER~LAB_TSCSSAs, \"gaussian\", NULL, NULL, \"tables_sm\")' -> Error in eval(predvars, data, env) : object 'LAB_TSCSSAs' not found\n"`

I think it's better to add your proposed text, since the user can access the names of the variables on the same tab it should be quite comfortable for the user.
